import {
	ApiProperty,
	ApiPropertyOptional,
	PartialType,
	PickType,
} from "@nestjs/swagger";
import { Type } from "class-transformer";
import { IsArray, IsInt, IsString } from "class-validator";
import { MatchShooter, MatchShooterCategory } from "src/entities";

// generated by the context from above

export class MatchShooterCategoryDto extends MatchShooterCategory {
	@ApiProperty({
		description: "Id of the match shooter category",
		example: 1,
	})
	@Type(() => Number)
	@IsInt()
	id: number;

	@ApiProperty({
		description: "Name of the match shooter category",
		example: "A",
	})
	@Type(() => String)
	@IsString()
	name: string;

	//TODO: relation
	matchShooters?: MatchShooter[];

	@ApiPropertyOptional({
		description: "Match shooters' id of the category",
		example: [1, 2, 3],
		readOnly: true,
	})
	@Type(() => Number)
	@IsArray()
	@IsInt({ each: true })
	readonly matchShooterIds?: number[];

	@ApiProperty({
		description: "Count of the match shooters in the category",
		example: 3,
		readOnly: true,
	})
	@Type(() => Number)
	@IsInt()
	readonly matchShooterCount: number;
}

export class CreateMatchShooterCategoryDto extends PickType(
	MatchShooterCategoryDto,
	["name", "matchShooters"] as const,
) {}

export class UpdateMatchShooterCategoryDto extends PartialType(
	CreateMatchShooterCategoryDto,
) {}
